services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    tty: true
    stdin_open: true
  
  boost:
    image: boost:1.88.0
    container_name: boost_container
    restart: unless-stopped
    build:
      context: ./boost
      dockerfile: boost.Dockerfile
    hostname: host
    ports:
      - "8080:8080"
    tty: true
  
  server:
    image: server:1.0
    container_name: server_container
    build:
      context: ./server
      dockerfile: server.Dockerfile
    depends_on:
      - postgres
      - boost
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres_user
      DB_PASSWORD: postgres_password
      DB_NAME: postgres_db
    ports:
      - "12340:12345" 
    volumes:
      - ./server:/server/data

  client:
    image: client:1.0
    container_name: client_container
    build:
      context: ./client
      dockerfile: client.Dockerfile
    depends_on:
      - boost
    ports:
      - "12341:12345"
    stdin_open: true
    tty: true
    volumes:
      - ./client:/client/data


volumes:
  pgdata:
    driver: local